isDebug = false
-- 加载离线版全局设置
require("GlobalSettings")
require("system.hotupdate")
require("util.ReadOnlyMeta")
require("unity_api")
memoryUtil = require("perf.memoryUtil")
mri = require("perf.MemoryReferenceInfo")
log("初始化lua内存工具")
if LuaMacro and LuaMacro.LUAPROFILER then
  memoryUtil.RecordTotal()
end
math.newrandomseed()
class = require("common.middleclass")
require("util.PlayerPrefs"):new()
eventManager = require("util.EventManager"):new()
configManager = require("util.ConfigManager"):new()
dataChangeManager = require("util.DataChangeManager"):new()
noticeManager = require("util.NoticeManager"):new()
npcAssistFleetMgr = require("util.NpcAssistFleetManager"):new()
prepareBattleMgr = require("util.PrepareBattleMgr"):new()
LuaUIPage = require("ui.framework.LuaUIPage")
log("初始化管理器和类工具")
log("初始化配置后")
require("PlatformWrapper")
platformManager = require("util.PlatformManager"):new()
require("common.stack")
require("common.functions")
require("common.constants")
require("common.custom_time")
log("初始化通用工具")
require("game2d.const2d")
require("util.CSUtil")
require("util.UGUIEventListener")
require("util.HeroSortHelper")
require("util.PeriodManager")
require("util.ScriptManager")
require("util.SoundHelper")
require("util.NoticeHelper")
require("util.SettingHelper")
require("util.RichTextUtil")
require("event.LuaEvent")
require("event.LuaCSharpEvent")
excMgr = require("util.ExceptionManager"):new()
pushNoticeManager = require("util.PushNoticeManager"):new()
require("logic.InitLogic")
require("data.InitData")
require("service.InitService")
log("初始化数据 服务 逻辑")
require("ui.UIHelper")
moduleManager = require("util.ModuleManager"):new()
require("util.ModelHelper")
require("util.RetentionHelper")
require("util.DropRewardsHelper")
require("util.TimelineHelp")
require("util.CSharpToLuaFunction")
require("game.battle.battleinit")
log("初始化帮助类")
BaseStage = require("stage.BaseStage")
stageMgr = require("util.StageManager"):new()
dataManager = require("util.DataManager"):new()
ShipCardItem = require("ui.page.ShipCardItem")
require("Common.GlobalRefrence")
require("Debug.GM.GMCMgr")
redDotManager = require("util.RedDotManager"):new()
UI3DModelManager = require("util.UI3DModelManager"):new()
conditionCheckManager = require("util.ConditionCheckManager"):new()
globalNoitceManager = require("util.GlobalNoitceManager"):new()
homeEnvManager = require("util.HomeEnvManager"):new()
plotManager = require("util.PlotManager"):new()
inputManager = require("util.InputManager"):new()
screenEffManager = require("util.ScreenEffManager"):new()
memoryUtil.LuaMemory("lua初始化结束")
shareManager = require("util.ShareManager"):new()
addictionManager = require("util.AddictionManager"):new()
TransitionManager = require("ui.page.Transition.TransitionManager")
queueManager = require("util.QueueManager"):new()
Replay = require("util.Replay"):new()
XR = require("util.XR"):new()
XR:CheckARSupport(true, false)
Face = require("util.Face"):new()
settlementSkillItemManager = require("ui.page.settlement.SettlementSkillItemManager"):new()
settlementExeManager = require("ui.page.settlement.SettlementExeManager"):new()
announcementManager = require("util.AnnouncementManager"):new()